name: tabs
description: The expense sharing app.

version: 1.0.1+7

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  firebase_auth: ^0.15.3+1
  cloud_firestore:
  provider:
  permission_handler:
  contacts_service:
  flutter_typeahead:
  flutter_money_formatter:
  timeago:
  flutter_spinkit:
  flutter_staggered_animations:
  google_sign_in:
  flutter_signin_button: ^1.0.0
  apple_sign_in: ^0.1.0
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/graphics/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 200
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 400
